---
title: "scatter_plots"
author: "Katharina E Hayer"
date: "10/21/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyr)
library(dplyr)
library(RColorBrewer)
library(ggrepel)
```

# Scatter plots

Read in data.

```{r read_in_data}
cols <- c('character','character','character','character','character','character',
          'numeric','character')
d = read.csv("~/Google Drive/AlignerBenchmarkLocal/default_summary.txt", head =T,sep = "\t", colClasses = cols)

d$algorithm = factor(d$algorithm)
nlevels(d$algorithm)
```

Calculate the mean an standard deviation.

```{r}
d$mean = rep(0,dim(d)[1])
d$sd = rep(0,dim(d)[1])


for (i in 1:dim(d)[1]) {
  #print(i)
  d$mean[i] = mean(d[d$species == d$species[i] & d$dataset == d$dataset[i] & d$algorithm == d$algorithm[i] & d$measurement == d$measurement[i] & d$level == d$level[i],]$value)
  d$sd[i] = sd(d[d$species == d$species[i] & d$dataset == d$dataset[i] & d$algorithm == d$algorithm[i] & d$measurement == d$measurement[i] & d$level == d$level[i],]$value) 
}
```

## Functions

Scatter plot version 1.

```{r}
plot_my_data_scatter <- function(data, measurement1, measurement2, title, filename, write_file = TRUE) {
  # data = k 
  # measurement one of #{recall, precision}
  print(measurement1)
  data$tmp1= data[,colnames(data) == measurement1]
  print(measurement2)
  data$color[data$color == "#F0E442"] = "cornflowerblue"
  data$tmp2 = data[,colnames(data) == measurement2]
  print(head(data))
  print(data$tmp2)
  data$algorithm = factor(data$algorithm)
  print(levels(data$algorithm))
  p = ggplot(data,aes(x=tmp1, y=tmp2, col = algorithm, shape= algorithm, label = algorithm)) + 
    geom_point(size=5) +
    #geom_text(aes(label = tmp), size = 3) +
    ggtitle(title) + theme_gray(base_size=20) + 
    scale_shape_manual(values=1:nlevels(data$algorithm) ) +
    xlab("Algorithm") + xlab(measurement1)+ ylab(measurement2)+ #ylim(c(-0.0001,1.0001)) +
    #scale_x_discrete(limits=data[order(data$tmp,decreasing = TRUE),]$algorithm)  + theme_gray(base_size=17) +#theme_light()+
    #theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)) + #scale_fill_brewer(palette="Accent") +
    #scale_fill_manual(values = data$color) +
    scale_color_manual(values = data$color) + 
    #scale_colour_brewer(palette = "Dark2") +
    #geom_text(hjust = 0, nudge_x = 0.005, check_overlap = TRUE) +
    #xlim(c(.875,1.03)) +
    theme(panel.background = element_rect(colour = "gray97", fill="gray97")) + 
    guides(fill=FALSE) 
  print(p)
  if (write_file) {
    ggsave(
      filename,
      width = 8.25,
      height = 5.75,
      dpi = 300
    )
  }
  #data$tmp <- NULL
}
```

Scatter plot version with labels.

```{r}
plot_my_data_scatter_labels <- function(data, measurement1, measurement2, title, filename, write_file = TRUE) {
  # data = k 
  # measurement one of #{recall, precision}
  print(measurement1)
  data$tmp1= data[,colnames(data) == measurement1]
  print(measurement2)
  data$color[data$color == "#F0E442"] = "cornflowerblue"
  data$tmp2 = data[,colnames(data) == measurement2]
  print(head(data))
  print(data$tmp2)
  data$algorithm = factor(data$algorithm)
  print(levels(data$algorithm))
  p = ggplot(data,aes(x=tmp1, y=tmp2, col = algorithm, shape= algorithm, label = algorithm)) + 
    geom_point(size=5) +
    #geom_text(aes(label = tmp), size = 3) +
    ggtitle(title) + theme_gray(base_size=20) + 
    scale_shape_manual(values=1:nlevels(data$algorithm) ) +
    xlab("Algorithm") + xlab(measurement1)+ ylab(measurement2)+ #ylim(c(-0.0001,1.0001)) +
    #scale_x_discrete(limits=data[order(data$tmp,decreasing = TRUE),]$algorithm)  + theme_gray(base_size=17) +#theme_light()+
    #theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)) + #scale_fill_brewer(palette="Accent") +
    #scale_fill_manual(values = data$color) +
    scale_color_manual(values = data$color) + 
    #scale_colour_brewer(palette = "Dark2") +
    #geom_text(hjust = 0, nudge_x = 0.005, check_overlap = TRUE) +
    #xlim(c(.875,1.03)) +
    theme(panel.background = element_rect(colour = "gray97", fill="gray97")) + 
    #geom_text_repel(point.padding = unit(0.25, "lines")) +
    geom_text_repel(point.padding = unit(0.25, "lines")) +
    guides(fill=FALSE) 
  print(p)
  if (write_file) {
    ggsave(
      filename,
      width = 8.25,
      height = 5.75,
      dpi = 300
    )
  }
  #data$tmp <- NULL
}
```


Scatter plot version with labels, but no shapes.

```{r}
plot_my_data_scatter_labels_shapes <- function(data, measurement1, measurement2, title, filename, write_file = TRUE) {
  # data = k 
  # measurement one of #{recall, precision}
  print(measurement1)
  data$tmp1= data[,colnames(data) == measurement1]
  print(measurement2)
  data$color[data$color == "#F0E442"] = "cornflowerblue"
  data$tmp2 = data[,colnames(data) == measurement2]
  print(head(data))
  print(data$tmp2)
  data$algorithm = factor(data$algorithm)
  print(levels(data$algorithm))
  xlim <- range( data$tmp1 )
  ylim <- range( data$tmp2 )
  xlim[2] = 1.01
  ylim[2] = 1.01
  p = ggplot(data,aes(x=tmp1, y=tmp2, col = algorithm, label = algorithm)) + 
    geom_point(size=3,alpha = 0.85) +
    #geom_text(aes(label = tmp), size = 3) +
    ggtitle(title) + theme_gray(base_size=20) + 
    scale_shape_manual(values=1:nlevels(data$algorithm) ) +
    xlab("Algorithm") + xlab(measurement1)+ ylab(measurement2)+ #ylim(c(-0.0001,1.0001)) +
    #scale_x_discrete(limits=data[order(data$tmp,decreasing = TRUE),]$algorithm)  + theme_gray(base_size=17) +#theme_light()+
    #theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)) + #scale_fill_brewer(palette="Accent") +
    #scale_fill_manual(values = data$color) +
    scale_color_manual(values = data$color) + 
    #scale_colour_brewer(palette = "Dark2") +
    #geom_text(hjust = 0, nudge_x = 0.005, check_overlap = TRUE) +
    #xlim(c(.875,1.03)) +
    theme(panel.background = element_rect(colour = "gray97", fill="gray97")) + 
    #geom_text_repel(point.padding = unit(0.25, "lines")) +
    geom_text_repel(force = 5, point.padding = unit(0.65, "lines"),arrow = arrow(length = unit(0.01, 'npc'))) +
    ylim(ylim) + xlim(xlim) + 
    guides(fill=FALSE) 
  print(p)
  if (write_file) {
    ggsave(
      filename,
      width = 8.25,
      height = 5.75,
      dpi = 300
    )
  }
  #data$tmp <- NULL
}
```

Scatter plot version with labels, but no shapes, different theme.

```{r}
plot_my_data_scatter_bw_theme <- function(data, measurement1, measurement2, title, filename, write_file = TRUE) {
  # data = k 
  # measurement one of #{recall, precision}
  print(measurement1)
  data$tmp1= data[,colnames(data) == measurement1]
  print(measurement2)
  data$color[data$color == "#F0E442"] = "cornflowerblue"
  data$tmp2 = data[,colnames(data) == measurement2]
  print(head(data))
  print(data$tmp2)
  data$algorithm = factor(data$algorithm)
  print(levels(data$algorithm))
  xlim <- range( data$tmp1 )
  ylim <- range( data$tmp2 )
  xlim[2] = 1.01
  ylim[2] = 1.01
  p = ggplot(data,aes(x=tmp1, y=tmp2, col = algorithm, label = algorithm)) + 
    geom_point(size=3,alpha = 0.85) +
    #geom_text(aes(label = tmp), size = 3) +
    ggtitle(title) + theme_bw(base_size=20) + 
    scale_shape_manual(values=1:nlevels(data$algorithm) ) +
    xlab("Algorithm") + xlab(measurement1)+ ylab(measurement2)+ #ylim(c(-0.0001,1.0001)) +
    #scale_x_discrete(limits=data[order(data$tmp,decreasing = TRUE),]$algorithm)  + theme_gray(base_size=17) +#theme_light()+
    #theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)) + #scale_fill_brewer(palette="Accent") +
    #scale_fill_manual(values = data$color) +
    scale_color_manual(values = data$color) + 
    #scale_colour_brewer(palette = "Dark2") +
    #geom_text(hjust = 0, nudge_x = 0.005, check_overlap = TRUE) +
    #xlim(c(.875,1.03)) +
    theme(panel.background = element_rect(colour = "gray97", fill="gray97")) + 
    #geom_text_repel(point.padding = unit(0.25, "lines")) +
    geom_text_repel(force = 5, point.padding = unit(0.65, "lines"),arrow = arrow(length = unit(0.01, 'npc'))) +
    ylim(ylim) + xlim(xlim) + 
    guides(fill=FALSE) 
  print(p)
  if (write_file) {
    ggsave(
      filename,
      width = 8.25,
      height = 5.75,
      dpi = 300
    )
  }
  #data$tmp <- NULL
}
```


## Plot the versions


```{r}
l  = spread(d[,c("species","dataset","replicate","level","algorithm",
                 "color","measurement","mean")], measurement, mean)
k = l[l$species == "human" & l$level == "READLEVEL",]
k = k[k$dataset == "t3",]
plot_my_data_scatter(k,"precision","recall","human read level","read_level/human_t3_READ_scatter.pdf",TRUE)
plot_my_data_scatter_labels(k,"precision","recall","human read level","read_level/human_t3_READ_scatter_labels.pdf", TRUE)
plot_my_data_scatter_labels_shapes(k,"precision","recall","human read level","read_level/human_t3_READ_scatter_labels_shapes.pdf", TRUE)
plot_my_data_scatter_bw_theme(k,"precision","recall","human read level","read_level/human_t3_READ_scatter_bw_theme.pdf", TRUE)
k = l[l$species == "human" & l$level == "READLEVEL",]
k = k[k$dataset == "t2",]
plot_my_data_scatter(k,"precision","recall","human read level","read_level/human_t2_READ_scatter.pdf",TRUE)
plot_my_data_scatter_labels(k,"precision","recall","human read level","read_level/human_t2_READ_scatter_labels.pdf", TRUE)
plot_my_data_scatter_labels_shapes(k,"precision","recall","human read level","read_level/human_t2_READ_scatter_labels_shapes.pdf", TRUE)
plot_my_data_scatter_bw_theme(k,"precision","recall","human read level","read_level/human_t2_READ_scatter_bw_theme.pdf", TRUE)
k = l[l$species == "human" & l$level == "READLEVEL",]
k = k[k$dataset == "t1",]
plot_my_data_scatter(k,"precision","recall","human read level","read_level/human_t1_READ_scatter.pdf",TRUE)
plot_my_data_scatter_labels(k,"precision","recall","human read level","read_level/human_t1_READ_scatter_labels.pdf", TRUE)
plot_my_data_scatter_labels_shapes(k,"precision","recall","human read level","read_level/human_t1_READ_scatter_labels_shapes.pdf", TRUE)
plot_my_data_scatter_bw_theme(k,"precision","recall","human read level","read_level/human_t1_READ_scatter_bw_theme.pdf", TRUE)

```



